# Github Actions Tutorials:
#
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
# https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners

name: Publish to Docker Hub on Push

on:
  push:
    branches: [ master ]

jobs:
  update-user-guide:
    name: Publish to Docker Hub on Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rxmicro-usage repo
        uses: actions/checkout@v2

      - name: Setup m2 local repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: hello-world-microservice-maven-${{ runner.os }}-cache

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build Micoservice
        run: mvn --fail-at-end -B verify --file pom.xml

      - name: Publish to Docker Hub
        run: |
          PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

          docker login --username=rxmicro --password=${{ secrets.DOCKER_PASSWORD }}
          docker tag hello-world-microservice rxmicro/hello-world-microservice:latest
          docker tag hello-world-microservice rxmicro/hello-world-microservice:$PROJECT_VERSION
          docker tag hello-world-microservice rxmicro/hello-world-microservice:$GITHUB_SHA

          docker push rxmicro/hello-world-microservice:latest
          docker push rxmicro/hello-world-microservice:$PROJECT_VERSION
          docker push rxmicro/hello-world-microservice:$GITHUB_SHA
